In [1]:
import pandas as pd
import numpy as np

In [13]:
X = pd.read_csv('../data/processed/feature_data_scaled_and_dummied')
y = pd.read_csv('../data/processed/target_data')

In [14]:
X.shape

(7043, 46)

In [15]:
y.shape

(7043, 1)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=101)

In [19]:
name = ['Gradient Boosting Class']
model = [GradientBoostingClassifier()]

In [18]:
results_data = {'Model Name':name}
results = pd.DataFrame(results_data)
results.index = name
results.drop('Model Name',axis=1,inplace=True)
results

Empty DataFrame
Columns: []
Index: [Gradient Boosting Class]

      Churn
834       1
1641      0
2707      1
2096      1
4878      0
2145      0
242       0
5219      0
1403      0
2616      1
148       0
1110      0
3010      0
3104      0
3898      0
5351      1
337       0
2858      0
4281      0
1441      0
4526      0
2538      0
2866      0
2383      0
1488      0
249       0
6487      0
1656      0
1484      0
2514      1
...     ...
2107      0
2931      0
1949      0
4467      0
2184      1
1530      1
4719      1
5971      0
49        0
6184      0
4573      0
908       0
3182      0
5824      0
4828      0
6460      1
3829      1
5032      0
2623      0
5764      0
5672      0
973       1
4079      0
4171      1
6141      1
599       0
5695      0
1361      1
1547      1
4959      1

[4718 rows x 1 columns]

In [26]:
clf = GradientBoostingClassifier()
predictions = clf.fit(X_train,y_train).predict(X_test)

C:\Users\sallwright\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [24]:
for i,name in enumerate(name):
    clf = model[i]
    predictions = clf.fit(X_train,y_train).predict(X_test)
    accuracy = accuracy_score(y_test,predictions)

C:\Users\sallwright\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

TypeError: 'numpy.float64' object is not callable

In [22]:
results

Empty DataFrame
Columns: []
Index: [Gradient Boosting Class]